/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#002045',
        'secondary': '#735c00',
        'secondary-container': '#fed65b',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#745c00',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary': '#242110',
        'tertiary-container': '#3a3623',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#a69f87',
        'tertiary-fixed': '#ebe2c8',
        'tertiary-fixed-dim': '#cec6ad',
        'on-tertiary-fixed': '#1f1c0b',
        'on-tertiary-fixed-variant': '#4c4733',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'background': '#faf9fd',
        'on-background': '#1a1c1e',
        'surface': '#faf9fd',
        'on-surface': '#1a1c1e',
        'surface-variant': '#e3e2e6',
        'on-surface-variant': '#43474e',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'shadow': '#000000',
        'surface-tint': '#455f88',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        'inverse-primary': '#adc7f7',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        'liturgical-purple': {
          50: '#f5f3ff',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
        },
        'liturgical-gold': {
          400: '#facc15',
          500: '#eab308',
          600: '#ca8a04',
        },
        'church-amber': '#f59e0b',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        gothic: ['"Cinzel"', '"Playfair Display"', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(139, 92, 246, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(139, 92, 246, 0.6)' },
        },
      },
    },
  },
  plugins: [],
}
