export interface ChurchAPISuccessResponseInterface {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  data: any;
  message: string;
  statusCode: number;
  success: boolean;
}

// imported to church_website\frontEnd\src\pages\Devotions\pages\NotificationPage.tsx
export interface Event {
  id: string;
  text: string;
  category: "jumuiya" | "csa";
  posted_by: string;
  createdAt: string;
  read: boolean;
  images?: string[]; // optional image URLs
}
export interface Props {
  isAdmin: boolean;
  events: Event[];
}

// imported to church_website\frontEnd\src\pages\Devotions\csaComparison\CsaComparison.tsx
export interface JumuiData {
  _id: string;
  totalAttempts: number;
  correctAttempts: number;
  accuracy: number;
}

// imported to church_website\frontEnd\src\pages\Devotions\individualStatus\IndividualProgress.tsx
export interface WeekData {
  _id: number;
  totalAttempts: number;
  correctAttempts: number;
}

// imported to church_website\frontEnd\src\pages\Devotions\individualStatus\IndividualProgress.tsx
export interface Summary {
  totalAttempts: number;
  correctAttempts: number;
}

// imported to church_website\frontEnd\src\pages\Devotions\jumuiyaStatus\JumuiyaDashboard.tsx
export interface JumuiyaStats {
  jumuiyaId: string;
  totalAttempts: number;
  correctAttempts: number;
}
export interface DashboardProps {
  jumuiyaId: number;
}


// imported at church_website\frontEnd\src\pages\Devotions\Adminpage\App.tsx
 export interface Member {
  id: number;
  jumuiaName: string;
}


// imported at church_website\frontEnd\src\pages\Devotions\pages\NotificationPage.tsx
 export interface SocketError {
  message?: string;
  code?: string;
  stack?: string;
  [key: string]: unknown; // fallback for unexpected fields
}

// imported at church_website\frontEnd\src\pages\Devotions\components\NotificationModal.tsx
 export interface fileUpload {
  id: number; // generated by backend
  public_id: string; // unique identifier from cloud storage (e.g. Cloudinary)
  url: string; // direct access URL
  format?: string; // optional: file format (e.g. 'jpg', '')
  resource_type?: string; // optional: 'image', 'video', 'raw', etc.
  created_at?: string; // optional: ISO timestamp
}
export interface NotificationPayload {
  title: string;
  message: string;
  images?: fileUpload[];
  posted_to: string; 
  status : string; // optional, e.g. "active", "inactive"
}

export interface NotificationModalProps {
  createNotification: (payload: NotificationPayload) => Promise<void>;
  onClose: () => void;
  roles: string[];
}