import { testDb as pool } from "../../Configs/dbConfig.js";
import { ChatEventEnum } from "../../constant.js";
import logger from "../../logger/winston.js";
import { emitSocketEvent } from "../../socket/index.js";
import { ApiError } from "../../utils/ApiError.js";

// /notifications-event/v1/event + payload
export const createNotification = async (req, res) => {
  const { title, message, images, posted_to, status } = req.body;

  //get the logged in user_id , from authentication middleware
  const member_id = req.user?.member_id;

  // check for criticals data before anything else , we can abstract it into a utility function , sanitize it , validate imputs , will do this later, if any field misses ,we return direct not after reaching this furthest endpoint function
  if (!title || !message || !posted_to) {
    logger.warn("⚠️ Missing required fields", { body: req.body });
    throw new ApiError(400, "Title, message, and posted_to are required");
  }
  //since this  function is doing multiple read and write operation at once then we cosider it as a transaction , of which it should be atomic if one db operation fails the entire fails also
  await pool.query("BEGIN");
  try {
    //insert the payload to the notification table for persistency , incase we have late commers we need to show them order of notification received
    const result = await pool.query(
      `INSERT INTO notifications (title, message, posted_to, member_id, status)
   VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`,
      [title, message, posted_to, member_id, status || "normal"],
    );

    const notif = result.rows[0];

    //perform bulk insert of images_id and notification_id  from the upload route to link them to notification_uploads ,
    // this is a result of m:N relationship where 1 Notification can contain 3 images , same to many images can be contained in 1 notification
    // remeber this image is aleady uploaded on its api url /files/v1/upload/ and we get a responce with the following data
    //   id: number; // generated by backend
    //   public_id: string; // unique identifier from cloud storage (e.g. Cloudinary)
    //   url: string; // direct access URL
    //   format?: string; // optional: file format (e.g. 'jpg', 'pdf')
    //   resource_type?: string; // optional: 'image', 'video', 'raw', etc.
    //   created_at?: string; // optional: ISO timestamp
    //this data + notification_id is what we are gonig to upload it to the table notification_uploads as mentioned early
    if (images && images.length > 0) {
      const publicIds = images.map((img) => img.public_id);
      const uploadRes = await pool.query(
        `SELECT id FROM uploads WHERE public_id = ANY($1)`,
        [publicIds],
      );
      const values = uploadRes.rows.map((row) => `('${notif.id}', ${row.id})`);
      if (values.length > 0) {
        await pool.query(
          `INSERT INTO notification_uploads (notification_id, upload_id)
       VALUES ${values.join(",")}`,
        );
      }
    }

    //normalise the payload such that if we add anything else we never breake the socket imteded data for consistency and later if we think to add anything to the table
    const payload = {
      id: notif.id,
      title: notif.title,
      message: notif.message,
      posted_by: notif.posted_by,
      posted_to: notif.posted_to,
      created_at: notif.created_at,
    };

    //emiit the event to the other members either in the csa room or jumui_<id> room level
    if (posted_to?.toLowerCase() === "csa") {
      emitSocketEvent(
        "CSA_NOTIFICATIONS", //this represent the default room which the user is being joined to on login if authentication succed , we dont want any member , but only authenticated once , thus security, if you tamper with token it will not work
        ChatEventEnum.NOTIFY_CSA_ON_NEW_NOTIFICATION_EVENT, //this is the event emmited which will be caught by client and display the payload to the user notification page
        payload,
      );
      logger.info("📡 Emitted CSA notification", { notificationId: notif.id });
    } else {
      emitSocketEvent(
        posted_to, //this is only useful when we have an admin who is at both csa and jumui level , so to track which room the user wants to send the notification , by default it falls under csa , but if explicitly declared it will go to jumuiya room of where the user tocken jumui_id directs us
        ChatEventEnum.NOTIFY_SPECIFIC_JUMUIA_ON_NEW_NOTIFICATION_EVENT,
        payload,
      );
      logger.info("📡 Emitted Jumuia notification", {
        jumuia: posted_to,
        notificationId: notif.id,
      });
    }
    //on succes we commit the transactions
    await pool.query("COMMIT");
    return res.status(201).json(notif);

  } catch (err) {
    //else if some went through we remove them and go back to the previous knowk checkpoint
    await pool.query("ROLLBACK");
    logger.error("❌ Error creating notification", {
      message: err.message,
      stack: err.stack,
      body: req.body,
    });
    return res.status(500).json({ error: "Error creating notification" });
  }
};

// "/notifications/:id"
export const updateNotification = async (req, res) => {
  const { id } = req.params;
  const { title, message, status } = req.body;

  if (!id) {
    logger.warn("⚠️ Missing notification ID");
    return res.status(400).json({ error: "Notification ID is required" });
  }

  try {
    logger.info("✏️ Updating notification", {
      notificationId: id,
      updates: { title, message, status },
    });

    const result = await pool.query(
      `UPDATE notifications 
       SET title=$1, message=$2, status=$3 
       WHERE id=$4 
       RETURNING *`,
      [title, message, status, id],
    );

    if (result.rows.length === 0) {
      logger.warn("⚠️ Notification not found", { notificationId: id });

      return res.status(404).json({
        error: "Notification not found",
      });
    }

    const updated = result.rows[0];

    logger.info("✅ Notification updated", {
      notificationId: updated.id,
    });

    // 🔹 5. Prepare payload
    const payload = {
      id: updated.id,
      title: updated.title,
      message: updated.message,
      status: updated.status,
      posted_to: updated.posted_to,
      updated_at: updated.updated_at,
    };

    // 🔹 6. Emit to correct room (NOT global)
    if (updated.posted_to?.toLowerCase() === "csa") {
      emitSocketEvent(
        "CSA_NOTIFICATIONS",
        ChatEventEnum.NOTIFICATION_UPDATED_EVENT,
        payload,
      );

      logger.info("📡 Emitted CSA notification update", {
        notificationId: updated.id,
      });
    } else {
      emitSocketEvent(
        updated.posted_to,
        ChatEventEnum.NOTIFICATION_UPDATED_EVENT,
        payload,
      );

      logger.info("📡 Emitted Jumuia notification update", {
        jumuia: updated.posted_to,
        notificationId: updated.id,
      });
    }
    return res.json(updated);
  } catch (err) {
    logger.error("❌ Error updating notification", {
      message: err.message,
      stack: err.stack,
      notificationId: id,
      body: req.body,
    });

    return res.status(500).json({
      error: "Error updating notification",
    });
  }
};

// "/notifications/:id"

export const deleteNotification = async (req, res) => {
  const { id } = req.params;

  if (!id) {
    logger.warn("⚠️ Missing notification ID");
    return res.status(400).json({
      error: "Notification ID is required",
    });
  }

  try {
    logger.info("🗑️ Deleting notification", {
      notificationId: id,
    });

    const existing = await pool.query(
      "SELECT * FROM notifications WHERE id=$1",
      [id],
    );

    if (existing.rows.length === 0) {
      logger.warn("⚠️ Notification not found", {
        notificationId: id,
      });

      return res.status(404).json({
        error: "Notification not found",
      });
    }

    const notification = existing.rows[0];

    await pool.query("DELETE FROM notifications WHERE id=$1", [id]);

    logger.info("✅ Notification deleted", {
      notificationId: id,
    });

    const payload = {
      id: notification.id,
      posted_to: notification.posted_to,
    };

    // 🔹 5. Emit to correct room (NOT global)
    if (notification.posted_to?.toLowerCase() === "csa") {
      emitSocketEvent(
        "CSA_NOTIFICATIONS",
        ChatEventEnum.NOTIFICATION_DELETE_EVENT,
        payload,
      );

      logger.info("📡 Emitted CSA notification deletion", {
        notificationId: id,
      });
    } else {
      emitSocketEvent(
        notification.posted_to,
        ChatEventEnum.NOTIFICATION_DELETE_EVENT,
        payload,
      );

      logger.info("📡 Emitted Jumuia notification deletion", {
        jumuia: notification.posted_to,
        notificationId: id,
      });
    }
    return res.sendStatus(204);
  } catch (err) {
    logger.error(" Error deleting notification", {
      message: err.message,
      stack: err.stack,
      notificationId: id,
    });

    return res.status(500).json({
      error: "Error deleting notification",
    });
  }
};

//function that receives a jumuiyaid , fetches all notification with the jumuia id  and any other notification where posted to is csa and return the notifications 

export const getNotification = async (req, res) => {
  const { jumuiya_id: jumuiyaId } = req.user;

  try {
    const result = await pool.query(
      `SELECT * FROM notifications 
       WHERE posted_to=$1 OR posted_to='csa' `,
      [jumuiyaId],
    );
    
    if (result.rows.length === 0) {
      logger.info("⚠️ No notifications found", {
        jumuiyaId,
      });
    }

    return res.json(result.rows);
  } catch (err) {
    logger.error("❌ Error fetching notifications", {
      message: err,
      stack: err.stack,
      jumuiyaId,
    });

    return res.status(500).json({
      error: "Error fetching notifications",
    });
  }
};